<div class="footer_bottom">
    <div class="container">
        <div class="row">
        <div class="col-sm-12">
            <div class="bottomftr_box">
                <?php echo $this->getLayout() ->createBlock('Magento\Cms\Block\Block') ->setBlockId('footer_bottom1') ->toHtml(); ?>
            </div>
            <div class="bottomftr_box">
                <?php echo $this->getLayout() ->createBlock('Magento\Cms\Block\Block') ->setBlockId('footer_bottom2') ->toHtml(); ?>
            </div>
            <div class="bottomftr_box">
                <?php echo $this->getLayout() ->createBlock('Magento\Cms\Block\Block') ->setBlockId('footer_bottom3') ->toHtml(); ?>
            </div>
            <div class="bottomftr_box">
                <?php echo $this->getLayout() ->createBlock('Magento\Cms\Block\Block') ->setBlockId('footer_bottom4') ->toHtml(); ?>
            </div>
        </div>
        </div>
    </div>
</div>
