<?php 
$brands = $this->getBrands();
?>
	<h4>D - G</h4>
	<ul class="read-more-wrap">
<?php  
$count = 1;
$class = "more-reading";
foreach (range('D', 'G') as $char) :?>
	<?php if(isset($brands[$char])):?>
			<?php foreach($brands[$char] as $_brand):?>
				<li class="<?php if($count>1){echo $class;}?>">
					<?php if($_brand->getUrlKey()):?>
						<a href="<?php echo $this->getUrl('brand').$_brand->getUrlKey()?>"><?php echo $_brand->getName();?></a>
					<?php else:?>
						<a href="<?php echo $this->getUrl('brand/view/',array('id'=>$_brand->getId()));?>"><?php echo $_brand->getName();?></a>
					<?php endif;?>
				</li>
				<?php $count++; ?>
			<?php endforeach;?>
	<?php endif;?>
<?php endforeach;?>
</ul>
<div class="read-more-trigger1">
                  <input type="checkbox" class="read-more-state" id="post-4" />
                  <label for="post-4" class="read-more-trigger m-read"></label>
</div>

<script type="text/javascript">

	require(['jquery'],function($){
		  $(".more-reading").hide();
	      $(document).ready(function(){
            $('.m-read').click( function(){
            	if($(".more-reading").is(":visible")){
			  	   $(".more-reading").hide();
			  	}else{
                   $(".more-reading").show();
			  	}
	      });
	
	});
});
</script>