<?php 
$brands = $this->getBrands();
$featured = $this->getFeaturedBrands();
$media = $this->getImageMediaPath();
?>

	

			
			


<section class="product_sec brands_sec">

        <div class="container">

          <div class="row">

            <div class="col-sm-12">

              <div class="product_head">

                <h4>Brands</h4> 

                </div>

              <div class="brandsub_slider">


<?php foreach($featured as $_fbrand):?>
                <div class="product_slide" id="product_slide_brand">
					<div class="productslide_img">

					<?php if($_fbrand->getUrlKey()):?>
						<a href="<?php echo $this->getUrl('brand').$_fbrand->getUrlKey()?>">
					<?php else:?>
						<a href="<?php echo $this->getUrl('brand/view/',array('id'=>$_fbrand->getId()));?>">
					<?php endif;?>
					<?php if($_fbrand->getLogo()):?>
							<img class="img-responsive" src="<?php echo $media.$_fbrand->getLogo() ?>" title="<?php echo $_fbrand->getName();?>" alt="<?php echo $_fbrand->getName();?>"/>
						<?php else:?>
						<span class="brand-title">
							<?php echo $_fbrand->getName();?>
						</span>
						<?php endif;?>
					</a>
						
					</div>
				</div>
<?php endforeach;?>



              </div>

            </div>

          </div>

        </div>

      </section>

<script type="text/javascript">
	require(['jquery', 'slick'], function($){ 
    //alert("ioioi");
       $(".brandsub_slider").slick({
        dots: false,
        infinite: true,
        centerMode: true,
        slidesToShow: 7,
        slidesToScroll: 1,
        autoplay:false,
        arrows:true,
      });
     
 });
</script>