<?php 
$brands = $this->getBrands();
?>

<div class="block block-compare" data-bind="scope: 'compareProducts'" data-role="compare-products-sidebar">
    <div class="filter_head">
        <h4 id="block-compare-heading" role="heading" aria-level="2"><?php echo __('Shop By Brands');?>:</h4>
    </div>
    <ul class="items">
    	<?php  
	foreach (range('0', '9') as $char) :?>
		<?php if(isset($brands[$char])):?>
<!-- 				<strong> # <?php echo $char;?></strong> -->
				<?php foreach($brands[$char] as $_brand):?>
					<li>
					<?php if($_brand->getUrlKey()):?>
						<a href="<?php echo $this->getUrl('brand').$_brand->getUrlKey()?>"><?php echo $_brand->getName();?></a>
					<?php else:?>
						<a href="<?php echo $this->getUrl('brand/view/',array('id'=>$_brand->getId()));?>"><?php echo $_brand->getName();?></a>
					<?php endif;?>
					</li>
				<?php endforeach;?>
		<?php endif;?>
	<?php endforeach;?>
	<?php  
	foreach (range('A', 'Z') as $char) :?>
		<?php if(isset($brands[$char])):?>
<!-- 				<strong> # <?php echo $char;?></strong> -->
				<?php foreach($brands[$char] as $_brand):?>
					<li>
					<?php if($_brand->getUrlKey()):?>
						<a href="<?php echo $this->getUrl('brand').$_brand->getUrlKey()?>"><?php echo $_brand->getName();?></a>
					<?php else:?>
						<a href="<?php echo $this->getUrl('brand/view/',array('id'=>$_brand->getId()));?>"><?php echo $_brand->getName();?></a>
					<?php endif;?>
					</li>
				<?php endforeach;?>
		<?php endif;?>
	<?php endforeach;?>
	</ul>
</div>
