<?php 
$categoryId = $this->getCategoryId();
$getProudctcollection = $block->getCategoryProduct($categoryId);
//$getProudctcollection = array_rand($getProudctcollection);
?>

                                       
                                       
                        
              


<section class="product_sec seller_sec">
        <div class="container">
          <div class="row">
            <div class="col-sm-12">
              <div class="product_head">
                <h4><?php echo $block->getCategory($categoryId); ?></h4>
              </div>
              <div class="product_slider">
              
<?php                      
foreach ($getProudctcollection as $product) :
?>
      <div class="product_slide">
                  <div class="productslide_img">
                    <a title="<?php echo $block->escapeHtml($product->getName()) ?>"
                                       href="<?php /* @escapeNotVerified */ echo $product->getProductUrl() ?>"
                                       class="product-item-link">
                  		<img src="<?php echo $block->getUrl('pub/media/catalog').'product'.$product->getImage(); ?>" class="img-responsive" alt="">
                   </a>
                    <div class="productslide_hover">
                      <ul>
                        <li>
                         <?php if ($product->isSaleable()): ?>
                              <?php $postParams = $block->getAddToCart($product); ?>
                              <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
                                  <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
                            
                                  <?php echo $block->getBlockHtml('formkey')?>
                                  <button type="submit"
                                          title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                          class="action fa fa-shopping-cart">
                                      <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                  </button>
                              </form>
                              <?php else: ?>
                                    <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                            <?php endif; ?>
                        </li>
                        <li>
                        <a href="#"
                           class="action towishlist"
                           title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                           aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                           data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlist($product); ?>'
                           data-action="add-to-wishlist"
                           role="button">
                        <i class="fa fa-heart" aria-hidden="true"></i>
                        </a>
                        </li>

                        <li>
                        <a href="#"
                           class="action tocompare"
                           title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                           aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                           data-post='<?php echo $block->getAddToCompare($product);?>'
                           role="button">
                            <i class="fa fa-eye" aria-hidden="true"></i>
                        </a>
                        </li>
                      </ul>
                    </div>
                  </div>
                  <div class="productslide_cnt">
                  <h5>Brand Name</h5>
                    <p> <a title="<?php echo $block->escapeHtml($product->getName()) ?>"
                                       href="<?php /* @escapeNotVerified */ echo $product->getProductUrl() ?>"
                                       class="product-item-link">
                                        <?php echo $block->escapeHtml($product->getName()) ?>
                                    </a></p>
                    <span class="product_price"><?php echo $block->getProductPriceHtml($product) ?></span>
                  </div>
                </div>
                
         
<?php endforeach; ?>

   </div>
            </div>
          </div>
        </div>
      </section>


<script type="text/x-magento-init">
{
    "[data-role=tocart-form], .form.map.checkout": {
        "catalogAddToCart": {}
    }
}
</script>

<script type="text/javascript">

    require(['jquery', 'slick'], function(jQuery){ 
    //alert("ioioi");
      jQuery(".product_slider").slick({
      dots: false,
      infinite: true,
      centerMode: true,
      slidesToShow: 4,
      slidesToScroll: 1,
      autoplay:false,
      arrows:true,
      });
     
 });
</script>