<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Form\Login $block */
?>
<?php
/**
 * Customer login form template
 *
 * @see \Magento\Customer\Block\Form\Login
 * @var $block \Magento\Customer\Block\Form\Login
 */
?>
<div class="col-sm-6">
<div class="create_account">
        <h4 id="" role="heading" aria-level="2"><?php /* @escapeNotVerified */ echo __('Registered Customers') ?></h4>

    <div class="block-content" aria-labelledby="block-customer-login-heading">
        <form class="form form-login login_form"
              action="<?php /* @escapeNotVerified */ echo $block->getPostActionUrl() ?>"
              method="post"
              id="login-form"
              data-mage-init='{"validation":{}}'>
            <?php echo $block->getBlockHtml('formkey'); ?>
            <fieldset class="fieldset login" data-hasrequired="<?php /* @escapeNotVerified */ //echo __('* Required Fields') ?>">
                <div class="field note"><?php /* @escapeNotVerified */ echo __('If you have an account with us, please log in.') ?></div>
                <div class="field email required form-group">
                    <label for="email"><?php /* @escapeNotVerified */ echo __('Email Address') ?></label>
                        <input name="login[username]" value="<?php echo $block->escapeHtml($block->getUsername()) ?>" <?php if ($block->isAutocompleteDisabled()) :?> autocomplete="off"<?php endif; ?> id="email" type="email" class="input-text" title="<?php /* @escapeNotVerified */ echo __('Email') ?>" data-validate="{required:true, 'validate-email':true}">
                </div>
                <div class="field password required form-group">
                    <label for="pass" ><?php /* @escapeNotVerified */ echo __('Password') ?></label>
                        <input name="login[password]" type="password" <?php if ($block->isAutocompleteDisabled()) :?> autocomplete="off"<?php endif; ?> class="input-text" id="pass" title="<?php /* @escapeNotVerified */ echo __('Password') ?>" data-validate="{required:true}">
                </div>
                <?php echo $block->getChildHtml('form_additional_info'); ?>
                    <div class="primary"><button type="submit" class="action pull-right create_btn" name="send" id="send2"><span><?php /* @escapeNotVerified */ echo __('Login') ?></span></button></div>
                    <div class="forgot_password"><a class="action remind" href="<?php /* @escapeNotVerified */ echo $block->getForgotPasswordUrl() ?>"><?php /* @escapeNotVerified */ echo __('Forgot Your Password?') ?></a></div>
                   <!--  <p ><?php echo __('* Required Fields') ?></p> -->

            </fieldset>
        </form>
    </div>
</div>
</div>
