<?php
/**
 * Category sidebar
 *
 * @var $block Sebwite\Sidebar\Block\Sidebar
 */
$categories = $block->getCategories();
$brands     = $block->getBrands();
?>

<style type="text/css">
	
	.expanded .fa-plus::before {
    	content: "\f068" !important;
    }
    
    .expand {
		cursor: pointer;
	}
</style>
<div class="filter_head">
    <h4><?php echo __('Categories'); ?></h4>
</div>

<ul class="o-list">

    <?php
    // Loop through categories
    foreach ( $categories as $category ) :
        ?>
        <li class="level0<?php echo($block->isActive($category) ? ' active' : ''); ?>">
            <a href="<?php echo $block->getCategoryUrl($category); ?>" title="<?php echo $category->getName(); ?>" class="<?php echo($block->isActive($category) ? ' active' : ''); ?>">
                <?php echo $category->getName(); ?>
            </a>
            <?php if ( $category->hasChildren() ) : ?>
                <span class="expand" id="expand-<?php echo $category->getId(); ?>"><?php echo $block->isActive($category) ? '<i class="fa fa-minus"></i>' : '<i class="fa fa-plus"></i>'; ?></span>
            <?php endif; ?>

            <?php echo $block->getChildCategoryView($category); ?>
        </li>
    <?php endforeach; ?>
</ul>

<script type="text/javascript">

jQuery(document).ready(function() {
	jQuery(".child-categories").hide();	
	jQuery(".expand").click(function() {
		var id = jQuery(this).attr("id");
		var cat_id = id.split("-");
		var ul_id = '#category-'+cat_id[1];
		jQuery(ul_id).toggle('slow');
		jQuery(this).toggleClass( "expanded", 1000, "expand" );
	});
});

	
</script>