<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

    <div class="filter_head"><h4><?php /* @escapeNotVerified */ echo __('Newsletter:') ?></h4></div>
        <form class="form subscribe"
            novalidate
            action="<?php /* @escapeNotVerified */ echo $block->getFormActionUrl() ?>"
            method="post"
            data-mage-init='{"validation": {"errorClass": "mage-error"}}'
            id="newsletter-validate-detail">
            <div class="news_letter">
                    <input name="email" type="email" id="newsletter"
                                placeholder="<?php /* @escapeNotVerified */ echo __('Enter your email address') ?>"
                                data-validate="{required:true, 'validate-email':true}"/>
                <button class="btn btn_subcr" title="<?php /* @escapeNotVerified */ echo __('Subscribe') ?>" type="submit">
                    <?php /* @escapeNotVerified */ echo __('Subscribe') ?>
                </button>
            </div>
        </form>

