<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * New Customer block template
 *
 * @var $block \Magento\Customer\Block\Form\Login\Info
 */
?>
<?php if ($block->getRegistration()->isAllowed()): ?>
<div class="col-sm-6">
<div class="create_account">
        <h4 id="" role="heading" aria-level="2"><?php /* @escapeNotVerified */ echo __('New Customers') ?></h4>
   <!--  <div class="block-content" aria-labelledby="block-new-customer-heading"> -->
        <p><?php /* @escapeNotVerified */ echo __('By creating an account with our store, you will be able to move through the checkout process faster, store multiple shipping addresses, view and track your orders in your account and more.') ?></p>
            <div class="primary">
                <a href="<?php /* @escapeNotVerified */ echo $block->getCreateAccountUrl() ?>" class="action pull-right create_btn"><?php /* @escapeNotVerified */ echo __('Create an Account') ?></a>
            </div>
</div>
</div>
<?php endif; ?>
